### ISSUE TITLE
Is the activation permanent?

### ISSUE THREAD

**Issue by deepindersinghbti** [TanjimReza/WindowsPP#1]
I opened CMD and entered the command **slmgr/xpr**. The result was : _This machine is permanently activated_. But the product key used ends with **3V66T**, which is a Windows 10 Generic key and is valid just for a period of 60 days, according to Microsoft. 

So will the activation using this product key be permanent or it will expire after 60 days?

**Comment by TanjimReza** [comment]
It'll not expire after 60days even though it shows generic key.

**Comment by deepindersinghbti** [comment]
Thank you so much for creating this amazing activator and also for such a quick response!
